[workspace]
resolver = "3"
members = [
  "crates/sim-platform-browser",
  "crates/sim-platform-web-shell",
  "crates/sim-platform-audio",
  "crates/sim-platform-core",
  "crates/sim-platform-model",
  "crates/sim-platform-midi",
  "crates/sim-lib-platform",
  "crates/sim-platform-bootstrap",
  "crates/sim-platform-construction",
  "crates/sim-platform-linux",
  "crates/sim-platform-macos",
  "crates/sim-platform-android",
  "crates/sim-platform-amazfit",
  "crates/sim-platform-halo",
  "crates/sim-platform-ios",
  "crates/sim-platform-windows",
  "crates/sim-platform-wasi",
  "crates/sim-platform-ubuntu-pc",
  "crates/sim-platform-ubuntu-rpi",
  "crates/sim-platform-sqlite",
  "crates/sim-viture-ffi",
  "crates/sim-table-fs",
  "xtask",
]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/sim-nest/sim-platform"
homepage = "https://github.com/sim-nest/sim-platform"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
