[package]
name = "sim-lib-platform"
version = "0.1.1"
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Pure loadable-facing platform manifest API"
publish = true

[dependencies]
sim-kernel = "0.4.0"
sim-platform-core = { version = "0.2.0", path = "../sim-platform-core" }

[dev-dependencies]
sim-kernel = { version = "0.4.0", features = ["test-support"] }

[lints]
workspace = true
